version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: isla_transfers
      MYSQL_PASSWORD: adminadmin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: adminadmin
    networks:
      - my_network
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: isla_transfers
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: adminadmin
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - db

volumes:
  db_data:
  wp_data:

networks:
  my_network: {}
